remote_theme: rundocs/jekyll-rtd-theme
markdown: kramdown
title: Prueba de titulo
lang: en
description: Write an awesome description for your new site here

topnav_title: Titulo
company_name: Copyright 2021 Santiago Arboleda
feedback_email: sanarboleda6@hotmail.com

# plugin options
readme_index:
  with_frontmatter: true
